--DROP DATABASE Cosecha_de_Aceitunas

CREATE DATABASE Cosecha_de_Aceitunas
GO
USE Cosecha_de_Aceitunas
GO

--DROP TABLE CA_Agricultura

GO

CREATE TABLE CA_Agricultuor
(
	CodigoA TINYINT NOT NULL, 
	Nombre VARCHAR(30) NOT NULL ,
	Direccion VARCHAR(40) NOT NULL,
	Telefono CHAR(9) NOT NULL,
	CodigoL TINYINT NOT NULL, 
	CONSTRAINT PK_CA_Lote PRIMARY KEY (CodigoA),
)

GO

--DROP TABLE CA_Lote

CREATE TABLE CA_Lote
(
	CodigoL TINYINT NOT NULL, 
	Peso TINYINT NOT NULL,
	Fecha_de_Recoleccion DATE NOT NULL,
	Variedad VARCHAR (15) NOT NULL,
	Metodo VARCHAR (10) NOT NULL, 
	CodigoA TINYINT NOT NULL,
	CodigoF TINYINT NOT NULL,
	CodigoR TINYINT NOT NULL, 
	CONSTRAINT PK_Lote PRIMARY KEY (CodigoL),
	CONSTRAINT FK_Lote_Agricultor FOREIGN KEY(CodigoL) REFERENCES CA_Agricultuor (CodigoA) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Lote_Finca FOREIGN KEY (CodigoL) REFERENCES CA_Finca (CodigoF) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Lote_Remesa FOREIGN KEY (CodigoL) REFERENCES CA_Remesa (CodigoR) ON DELETE NO ACTION ON UPDATE CASCADE,
)

GO

--DROP TABLE CA_Finca

CREATE TABLE CA_Finca
(
	CodigoF TINYINT NOT NULL, 
	NombreF VARCHAR (30) NOT NULL,
	Municipio VARCHAR(30) NOT NULL,
	Distancia_a_Cooperativa TINYINT NOT NULL,
	CodigoL TINYINT NOT NULL,
	CONSTRAINT PK_lLote PRIMARY KEY (CodigoF),
)

GO

--DROP TABLE CA_Remesa

CREATE TABLE CA_Remesa
(
	CodigoR TINYINT NOT NULL, 
	Litros TINYINT NOT NULL,
	Acidez TINYINT NOT NULL,
	CodigoL TINYINT NOT NULL,
	CodigoD TINYINT NOT NULL,
	CONSTRAINT PK_CA_Remesa PRIMARY KEY (CodigoR),
	CONSTRAINT FK_Remesa_Distribuidora FOREIGN KEY (CodigoR) REFERENCES CA_Distribuidora (CodigoD) ON DELETE NO ACTION ON UPDATE CASCADE,
)

GO

--DROP TABLE CA_Distribuidora

CREATE TABLE CA_Distribuidora
(
	CodigoD TINYINT NOT NULL,
	Nombre VARCHAR(30) NOT NULL, 
	Telefono VARCHAR(9) NOT NULL, 
	Direccion VARCHAR(40) NOT NULL,
	CodigoR TINYINT NOT NULL,
	CONSTRAINT PK_CA_Distribuidora PRIMARY KEY (CodigoD),
)

GO

